steps:
# docker training-gpu
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'setup/docker/trainer_pl_gpu.dockerfile', '-t', 'gcr.io/sensi-anal/training_gpu:0.0.1', './']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sensi-anal/trainer_pl_gpu:0.0.1']
# docker training-cpu
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'setup/docker/trainer_pl_cpu.dockerfile', '-t', 'gcr.io/sensi-anal/training_cpu:0.0.1', './']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sensi-anal/training_cpu:0.0.1']
# fastapipredict cpu
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'setup/docker/fastapipredict_cpu.dockerfile', '-t', 'gcr.io/sensi-anal/fastapipredict_cpu:0.0.1', './']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sensi-anal/fastapipredict_cpu:0.0.1']
# fastapipredict0gpu
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'setup/docker/fastapipredict_gpu.dockerfile', '-t', 'gcr.io/sensi-anal/fastapipredict_gpu:0.0.1', './']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sensi-anal/fastapipredict_gpu:0.0.1']
images:
  - gcr.io/sensi-anal/fastapipredict_gpu
  - 
timeout: 20000s
