steps:
# docker training-gpu
- name: 'gcr.io/sensi-anal/training_gpu'
  args: ['build', '-f', 'setup/docker/trainer_pl_gpu.dockerfile']

# docker training-cpu
- name: 'gcr.io/sensi-anal/training_cpu'
  args: ['build', '-f', 'setup/docker/trainer_pl_cpu.dockerfile']

# fastapipredict
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sensi-anal/fastapicloudb:0.0.1', "--file", "fastapipredict.dockerfile", '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sensi-anal/fastapicloudb:0.0.1']
images:
  - gcr.io/sensi-anal/fastapicloudb
