steps:
# docker fastapi
- name: 'gcr.io/sensi-anal/fastapicbuild'
  args: ['build', '-f', 'setup/docker/fastapipredict.dockerfile']

# docker training-gpu
- name: 'gcr.io/sensi-anal/training_gpu'
  args: ['build', '-f', 'setup/docker/trainer_pl_gpu.dockerfile']

# docker training-cpu
- name: 'gcr.io/sensi-anal/training_cpu'
  args: ['build', '-f', 'setup/docker/trainer_pl_cpu.dockerfile']
