optimizer:
  #  Adam-oriented deep learning
  _target_: transformers.AdamW
  #  These are all default parameters for the Adam optimizer
  lr: 0.001
  betas: [ 0.9, 0.999 ]
  eps: 1e-08
  weight_decay: 0

use_lr_scheduler: True
lr_scheduler:
  num_warmup_steps: 999
