---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapitransformer
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: predictor
          image: gcr.io/sensi-anal/fastapipredict:0.0.1
          ports:
            - containerPort: 80