name: build-docs

on:
  workflow_run:
    workflows: ["Python3.9 pytest"]
    branches: [master]
    types: [completed]
  # on releases, future
  release:
    types: [published, created, edited]
  pull_request:
    branches:
      - master
      - dev

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    # only run if pytest successfull
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: 'pip'
        cache-dependency-path: '**/requirements*.txt'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
        pip install -e .

    - name: create shinx docs
      # create shpinx api autodocs of opensentiment and move them to docs
      # makefile: make html build the the docs/_build/html/
      run: |
        sphinx-apidoc -o ./docs ./opensentiment 
        cd docs
        make html
    
    - name: Commit documentation changes
      run: |
        mkdir -p gh-pages
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add . 
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.

    - name: Push changes to github repo/gh-pages
      uses: ad-m/github-push-action@master
      with:
         branch: gh-pages
         directory: gh-pages
        #  github_token: ${{ secrets.SECRET_TOKEN }}