name: Python 3.9 pip unittests lint

on: 
  pull_request:
    branches:
    - master
    - dev
  push:
    branches: 
    - master
    - dev
    
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: 'pip'
        cache-dependency-path: '**/requirements*.txt'
        
#     - name: Add conda to system path # not using conda
#       run: |
#         # $CONDA is an environment variable pointing to the root of the miniconda directory
#         echo $CONDA/bin >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -e .
    # - name: Install test dependencies # done already in requirements
    #   run: |
    #     pip install flake8 pytest coverage isort 
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics    
    - name: Test with pytest
      run: |
        pytest tests

    # - name: Generate Report
    #     run: |
    #       coverage run -m pytest tests
    #       coverage xml
    #   - name: Upload coverage to Codecov
    #     uses: codecov/codecov-action@v2

